language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
    - VERBOSE=1
    - OTIO_AAF_PYTHON_LIB=

install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - clone https://github.com/markreidvfx/pyaaf.git /tmp/pyaaf && \
    cd /tmp/pyaaf && \
    python setup.py build_ext --inplace && \
    make dev && \
    make build && \
    make install
  - pip install pep8 pyflakes flake8 coverage Pillow

script:
  - make lint
  - make test
  - make test-contrib
  - make coverage
