language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
    - VERBOSE=1
    - OTIO_AAF_PYTHON_LIB=

install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - wget -qO /tmp/pyaaf.zip https://github.com/markreidvfx/pyaaf/archive/master.zip &&
    cd /tmp &&
    ls -latrh &&
    unzip pyaaf.zip &&
    ls -latrh &&
    cd pyaaf-master &&
    ls -latrh &&
    python setup.py build_ext --inplace &&
    make dev &&
    make build &&
    make install
  - pip install pep8 pyflakes flake8 coverage Pillow

script:
  - make lint
  - make test
  - make test-contrib
  - make coverage
