language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pep8 pyflakes flake8 coverage Pillow

jobs:
  include:
    - stage: test
      script:
        - make lint
        - make test
        - make test-contrib
        - make coverage
    - stage: test-contrib
      env: PYAAF=PyAAF-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl
      before_install: wget -qO /tmp/${PYAAF} "https://github.com/markreidvfx/pyaaf/releases/download/v1.0.0/${PYAAF}"
      install:
        - pip install --upgrade pip setuptools wheel
        - pip install /tmp/${PYAAF}
      script: make test-contrib
